#!/bin/bash

set -e
. /usr/share/yunohost/helpers

do_pre_regen() {
  pending_dir=$1

  cd /usr/share/yunohost/templates/mysql

  # Legacy code to get rid of /etc/yunohost/mysql ...
  # Nowadays, we can simply run mysql while being run as root of unix_socket/auth_socket is enabled...
  if [ -f /etc/yunohost/mysql ]; then

      # This is a trick to check if we're able to use mysql without password
      # Expect instances installed in stretch to already have unix_socket
      #configured, but not old instances from the jessie/wheezy era
      if ! echo "" | mysql
      then
          password="$(cat /etc/yunohost/mysql)"
          # Enable plugin unix_socket for root on localhost
          mysql -u root -p"$password" <<< "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED WITH unix_socket WITH GRANT OPTION;"
      fi

      # If now we're able to login without password, drop the mysql password
      if echo "" | mysql
      then
          rm /etc/yunohost/mysql
      fi
  fi


  install -D -m 644 my.cnf "${pending_dir}/etc/mysql/my.cnf"
}

do_post_regen() {
  regen_conf_files=$1

  [[ -z "$regen_conf_files" ]] \
    || service mysql restart
}

FORCE=${2:-0}
DRY_RUN=${3:-0}

case "$1" in
  pre)
    do_pre_regen $4
    ;;
  post)
    do_post_regen $4
    ;;
  *)
    echo "hook called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
